/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bigbaldy_jnitest_MainActivity */

#ifndef _Included_bigbaldy_jnitest_MainActivity
#define _Included_bigbaldy_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bigbaldy_jnitest_MainActivity
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bigbaldy_jnitest_MainActivity_getStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
